version: "3.9"

services:
  app:
    image: node:18.12-alpine
    command: sh -c "npm i && npm run sync:tables && npm run dev"
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    working_dir: /app
    volumes:
      - ./:/app

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
